version: '3.9'
services:
  mysql:
    image: mysql:8.3
    container_name: sigil_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sigil_db
    ports:
      - '3308:3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
