export const ABI = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  { inputs: [], name: 'AccountAlreadyExists', type: 'error' },
  { inputs: [], name: 'AccountNotFound', type: 'error' },
  { inputs: [], name: 'DailySignalLimitExceeded', type: 'error' },
  { inputs: [], name: 'FidAlreadyRegistered', type: 'error' },
  { inputs: [], name: 'InsufficientUSDC', type: 'error' },
  { inputs: [], name: 'InvalidCA', type: 'error' },
  { inputs: [], name: 'InvalidDirection', type: 'error' },
  { inputs: [], name: 'InvalidFid', type: 'error' },
  { inputs: [], name: 'InvalidTimeframe', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'OwnableInvalidOwner',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'OwnableUnauthorizedAccount',
    type: 'error',
  },
  { inputs: [], name: 'SignalAlreadyResolved', type: 'error' },
  { inputs: [], name: 'SignalNotExpired', type: 'error' },
  { inputs: [], name: 'SignalNotFound', type: 'error' },
  { inputs: [], name: 'USDCTransferFailed', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
    ],
    name: 'AccountCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'signalId',
        type: 'uint256',
      },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'ca', type: 'address' },
      {
        indexed: false,
        internalType: 'uint8',
        name: 'direction',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'uint8',
        name: 'timeframe',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'expiresAt',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: 'isSubscriber',
        type: 'bool',
      },
    ],
    name: 'SignalCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'signalId',
        type: 'uint256',
      },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      { indexed: false, internalType: 'bool', name: 'won', type: 'bool' },
    ],
    name: 'SignalResolved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'expiresAt',
        type: 'uint64',
      },
    ],
    name: 'Subscribed',
    type: 'event',
  },
  {
    inputs: [],
    name: 'DAILY_SIGNAL_LIMIT',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_TIMEFRAME_HOURS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MIN_TIMEFRAME_HOURS',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'SUBSCRIPTION_DURATION',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'SUBSCRIPTION_PRICE',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'USDC',
    outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'accounts',
    outputs: [
      { internalType: 'uint256', name: 'fid', type: 'uint256' },
      { internalType: 'bool', name: 'isSubscribed', type: 'bool' },
      { internalType: 'uint64', name: 'subscriptionExpiry', type: 'uint64' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'fid', type: 'uint256' }],
    name: 'createAccount',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'dailySignalCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'deploymentTimestamp',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'fidToAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getAccount',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'fid', type: 'uint256' },
          { internalType: 'bool', name: 'isSubscribed', type: 'bool' },
          {
            internalType: 'uint64',
            name: 'subscriptionExpiry',
            type: 'uint64',
          },
        ],
        internalType: 'struct ProjectLighthouseV14.Account',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getContractStats',
    outputs: [
      { internalType: 'uint256', name: '_totalSignals', type: 'uint256' },
      { internalType: 'uint256', name: '_totalAccounts', type: 'uint256' },
      { internalType: 'uint256', name: '_usdcBalance', type: 'uint256' },
      {
        internalType: 'uint256',
        name: '_deploymentTimestamp',
        type: 'uint256',
      },
      { internalType: 'uint256', name: '_currentDay', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getCurrentDay',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'fid', type: 'uint256' }],
    name: 'getCurrentDaySignalCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'fid', type: 'uint256' },
      { internalType: 'uint256', name: 'day', type: 'uint256' },
    ],
    name: 'getDailySignalCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getRemainingDailySignals',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'signalId', type: 'uint256' }],
    name: 'getSignal',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'fid', type: 'uint256' },
          { internalType: 'address', name: 'ca', type: 'address' },
          { internalType: 'uint8', name: 'direction', type: 'uint8' },
          { internalType: 'uint8', name: 'timeframe', type: 'uint8' },
          { internalType: 'uint64', name: 'createdAt', type: 'uint64' },
          { internalType: 'uint64', name: 'expiresAt', type: 'uint64' },
          { internalType: 'bool', name: 'isResolved', type: 'bool' },
          { internalType: 'bool', name: 'won', type: 'bool' },
        ],
        internalType: 'struct ProjectLighthouseV14.Signal',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint8', name: 'timeframe', type: 'uint8' }],
    name: 'getTimeframeHours',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'fid', type: 'uint256' }],
    name: 'getUserSignals',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'isSubscribed',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nextSignalId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'signalId', type: 'uint256' },
      { internalType: 'bool', name: 'won', type: 'bool' },
    ],
    name: 'resolveSignal',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'ca', type: 'address' },
      { internalType: 'uint8', name: 'direction', type: 'uint8' },
      { internalType: 'uint8', name: 'timeframe', type: 'uint8' },
    ],
    name: 'signal',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'signals',
    outputs: [
      { internalType: 'uint256', name: 'fid', type: 'uint256' },
      { internalType: 'address', name: 'ca', type: 'address' },
      { internalType: 'uint8', name: 'direction', type: 'uint8' },
      { internalType: 'uint8', name: 'timeframe', type: 'uint8' },
      { internalType: 'uint64', name: 'createdAt', type: 'uint64' },
      { internalType: 'uint64', name: 'expiresAt', type: 'uint64' },
      { internalType: 'bool', name: 'isResolved', type: 'bool' },
      { internalType: 'bool', name: 'won', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'subscribe',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalAccounts',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalSignals',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'userSignals',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
    name: 'withdrawUSDC',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
