export const ABI = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  { inputs: [], name: 'AccountAlreadyExists', type: 'error' },
  { inputs: [], name: 'AccountNotFound', type: 'error' },
  { inputs: [], name: 'AlreadySignaledToday', type: 'error' },
  { inputs: [], name: 'FidAlreadyRegistered', type: 'error' },
  { inputs: [], name: 'InsufficientJBM', type: 'error' },
  { inputs: [], name: 'InvalidExitMarketCapsLength', type: 'error' },
  { inputs: [], name: 'InvalidFid', type: 'error' },
  { inputs: [], name: 'InvalidMarketCap', type: 'error' },
  { inputs: [], name: 'InvalidTicker', type: 'error' },
  { inputs: [], name: 'InvalidTokenAddress', type: 'error' },
  { inputs: [], name: 'InvalidTokenCount', type: 'error' },
  { inputs: [], name: 'InvalidUsername', type: 'error' },
  { inputs: [], name: 'JBMTransferFailed', type: 'error' },
  { inputs: [], name: 'NoRetryAvailable', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'OwnableInvalidOwner',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'OwnableUnauthorizedAccount',
    type: 'error',
  },
  { inputs: [], name: 'SessionAlreadyActive', type: 'error' },
  { inputs: [], name: 'SessionExpiredError', type: 'error' },
  { inputs: [], name: 'SessionNotActive', type: 'error' },
  { inputs: [], name: 'SignalNotActive', type: 'error' },
  { inputs: [], name: 'SignalNotFound', type: 'error' },
  { inputs: [], name: 'UserBanned', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'timestamp',
        type: 'uint256',
      },
    ],
    name: 'AccountBanned',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      {
        indexed: false,
        internalType: 'string',
        name: 'pfpUrl',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'username',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'timestamp',
        type: 'uint256',
      },
    ],
    name: 'AccountCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      {
        components: [
          { internalType: 'address', name: 'ca', type: 'address' },
          { internalType: 'string', name: 'ticker', type: 'string' },
        ],
        indexed: false,
        internalType: 'struct ProjectLighthouseV11.DefaultToken[8]',
        name: 'defaultTokens',
        type: 'tuple[8]',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'timestamp',
        type: 'uint256',
      },
    ],
    name: 'DefaultTokensUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'jbmPaid',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'timestamp',
        type: 'uint256',
      },
    ],
    name: 'RetryPurchased',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'timestamp',
        type: 'uint256',
      },
    ],
    name: 'SessionExpired',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      {
        components: [
          { internalType: 'address', name: 'ca', type: 'address' },
          { internalType: 'string', name: 'ticker', type: 'string' },
        ],
        indexed: false,
        internalType: 'struct ProjectLighthouseV11.DefaultToken[8]',
        name: 'defaultTokens',
        type: 'tuple[8]',
      },
      { indexed: false, internalType: 'bool', name: 'isRetry', type: 'bool' },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'startTime',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'expiresAt',
        type: 'uint256',
      },
    ],
    name: 'SessionStarted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'signalId',
        type: 'uint256',
      },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      {
        components: [
          { internalType: 'address', name: 'ca', type: 'address' },
          { internalType: 'uint256', name: 'mc', type: 'uint256' },
          { internalType: 'string', name: 'ticker', type: 'string' },
          { internalType: 'string', name: 'tokenImageUrl', type: 'string' },
          { internalType: 'uint256', name: 'prizeInUSDC', type: 'uint256' },
          {
            internalType: 'enum ProjectLighthouseV11.Direction',
            name: 'direction',
            type: 'uint8',
          },
        ],
        indexed: false,
        internalType: 'struct ProjectLighthouseV11.TokenPrediction[8]',
        name: 'tokens',
        type: 'tuple[8]',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'expiresAt',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'timestamp',
        type: 'uint256',
      },
    ],
    name: 'SignalCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'signalId',
        type: 'uint256',
      },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      {
        indexed: false,
        internalType: 'enum ProjectLighthouseV11.Status',
        name: 'status',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'uint8',
        name: 'correctPredictions',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'timestamp',
        type: 'uint256',
      },
    ],
    name: 'SignalSettled',
    type: 'event',
  },
  {
    inputs: [],
    name: 'JBM_RETRY_COST',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'JBM_TOKEN',
    outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_USERNAME_LENGTH',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'SESSION_DURATION',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'accounts',
    outputs: [
      { internalType: 'uint256', name: 'fid', type: 'uint256' },
      { internalType: 'string', name: 'pfpUrl', type: 'string' },
      { internalType: 'string', name: 'username', type: 'string' },
      { internalType: 'bool', name: 'isBanned', type: 'bool' },
      { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'banAccount',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'fid', type: 'uint256' },
      { internalType: 'string', name: 'pfpUrl', type: 'string' },
      { internalType: 'string', name: 'username', type: 'string' },
    ],
    name: 'createAccount',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'currentSession',
    outputs: [
      { internalType: 'address', name: 'user', type: 'address' },
      { internalType: 'uint256', name: 'fid', type: 'uint256' },
      { internalType: 'uint256', name: 'startTime', type: 'uint256' },
      { internalType: 'bool', name: 'isActive', type: 'bool' },
      { internalType: 'bool', name: 'usedRetry', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'deploymentTimestamp',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'fidToAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getAccount',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'fid', type: 'uint256' },
          { internalType: 'string', name: 'pfpUrl', type: 'string' },
          { internalType: 'string', name: 'username', type: 'string' },
          { internalType: 'bool', name: 'isBanned', type: 'bool' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
        ],
        internalType: 'struct ProjectLighthouseV11.Account',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'fid', type: 'uint256' }],
    name: 'getAccountByFid',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'fid', type: 'uint256' },
          { internalType: 'string', name: 'pfpUrl', type: 'string' },
          { internalType: 'string', name: 'username', type: 'string' },
          { internalType: 'bool', name: 'isBanned', type: 'bool' },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
        ],
        internalType: 'struct ProjectLighthouseV11.Account',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getActiveSession',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'user', type: 'address' },
          { internalType: 'uint256', name: 'fid', type: 'uint256' },
          { internalType: 'uint256', name: 'startTime', type: 'uint256' },
          { internalType: 'bool', name: 'isActive', type: 'bool' },
          { internalType: 'bool', name: 'usedRetry', type: 'bool' },
        ],
        internalType: 'struct ProjectLighthouseV11.Session',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'fid', type: 'uint256' }],
    name: 'getAddressByFid',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getContractStats',
    outputs: [
      { internalType: 'uint256', name: '_totalSignals', type: 'uint256' },
      { internalType: 'uint256', name: '_totalAccounts', type: 'uint256' },
      {
        internalType: 'uint256',
        name: '_deploymentTimestamp',
        type: 'uint256',
      },
      { internalType: 'uint256', name: '_jbmBalance', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getCurrentDay',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'limit', type: 'uint256' }],
    name: 'getRecentSignals',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'fid', type: 'uint256' },
          {
            components: [
              { internalType: 'address', name: 'ca', type: 'address' },
              { internalType: 'uint256', name: 'mc', type: 'uint256' },
              { internalType: 'string', name: 'ticker', type: 'string' },
              { internalType: 'string', name: 'tokenImageUrl', type: 'string' },
              { internalType: 'uint256', name: 'prizeInUSDC', type: 'uint256' },
              {
                internalType: 'enum ProjectLighthouseV11.Direction',
                name: 'direction',
                type: 'uint8',
              },
            ],
            internalType: 'struct ProjectLighthouseV11.TokenPrediction[8]',
            name: 'tokens',
            type: 'tuple[8]',
          },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'uint256', name: 'expiresAt', type: 'uint256' },
          {
            internalType: 'enum ProjectLighthouseV11.Status',
            name: 'status',
            type: 'uint8',
          },
          { internalType: 'uint8', name: 'correctPredictions', type: 'uint8' },
        ],
        internalType: 'struct ProjectLighthouseV11.Signal[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getSessionTimeRemaining',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'signalId', type: 'uint256' }],
    name: 'getSignal',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'fid', type: 'uint256' },
          {
            components: [
              { internalType: 'address', name: 'ca', type: 'address' },
              { internalType: 'uint256', name: 'mc', type: 'uint256' },
              { internalType: 'string', name: 'ticker', type: 'string' },
              { internalType: 'string', name: 'tokenImageUrl', type: 'string' },
              { internalType: 'uint256', name: 'prizeInUSDC', type: 'uint256' },
              {
                internalType: 'enum ProjectLighthouseV11.Direction',
                name: 'direction',
                type: 'uint8',
              },
            ],
            internalType: 'struct ProjectLighthouseV11.TokenPrediction[8]',
            name: 'tokens',
            type: 'tuple[8]',
          },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'uint256', name: 'expiresAt', type: 'uint256' },
          {
            internalType: 'enum ProjectLighthouseV11.Status',
            name: 'status',
            type: 'uint8',
          },
          { internalType: 'uint8', name: 'correctPredictions', type: 'uint8' },
        ],
        internalType: 'struct ProjectLighthouseV11.Signal',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'fid', type: 'uint256' }],
    name: 'getUserActiveSignals',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'fid', type: 'uint256' },
          {
            components: [
              { internalType: 'address', name: 'ca', type: 'address' },
              { internalType: 'uint256', name: 'mc', type: 'uint256' },
              { internalType: 'string', name: 'ticker', type: 'string' },
              { internalType: 'string', name: 'tokenImageUrl', type: 'string' },
              { internalType: 'uint256', name: 'prizeInUSDC', type: 'uint256' },
              {
                internalType: 'enum ProjectLighthouseV11.Direction',
                name: 'direction',
                type: 'uint8',
              },
            ],
            internalType: 'struct ProjectLighthouseV11.TokenPrediction[8]',
            name: 'tokens',
            type: 'tuple[8]',
          },
          { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
          { internalType: 'uint256', name: 'expiresAt', type: 'uint256' },
          {
            internalType: 'enum ProjectLighthouseV11.Status',
            name: 'status',
            type: 'uint8',
          },
          { internalType: 'uint8', name: 'correctPredictions', type: 'uint8' },
        ],
        internalType: 'struct ProjectLighthouseV11.Signal[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getUserDailyStatus',
    outputs: [
      { internalType: 'bool', name: 'hasSignaledToday', type: 'bool' },
      { internalType: 'bool', name: 'hasUsedRetry', type: 'bool' },
      { internalType: 'bool', name: 'canSignal', type: 'bool' },
      { internalType: 'bool', name: 'canRetry', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'fid', type: 'uint256' }],
    name: 'getUserDefaultTokens',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'ca', type: 'address' },
          { internalType: 'string', name: 'ticker', type: 'string' },
        ],
        internalType: 'struct ProjectLighthouseV11.DefaultToken[8]',
        name: '',
        type: 'tuple[8]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getUserJBMBalance',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'fid', type: 'uint256' }],
    name: 'getUserSignals',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'lastSignalDay',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'loadMiniapp',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nextSignalId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'purchaseRetry',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: 'ca', type: 'address' },
          { internalType: 'string', name: 'ticker', type: 'string' },
        ],
        internalType: 'struct ProjectLighthouseV11.DefaultToken[8]',
        name: 'defaultTokens',
        type: 'tuple[8]',
      },
    ],
    name: 'setDefaultTokens',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'signalId', type: 'uint256' },
      {
        internalType: 'uint256[8]',
        name: 'exitMarketCaps',
        type: 'uint256[8]',
      },
    ],
    name: 'settleSignal',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'signals',
    outputs: [
      { internalType: 'uint256', name: 'fid', type: 'uint256' },
      { internalType: 'uint256', name: 'createdAt', type: 'uint256' },
      { internalType: 'uint256', name: 'expiresAt', type: 'uint256' },
      {
        internalType: 'enum ProjectLighthouseV11.Status',
        name: 'status',
        type: 'uint8',
      },
      { internalType: 'uint8', name: 'correctPredictions', type: 'uint8' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: 'ca', type: 'address' },
          { internalType: 'uint256', name: 'mc', type: 'uint256' },
          { internalType: 'string', name: 'ticker', type: 'string' },
          { internalType: 'string', name: 'tokenImageUrl', type: 'string' },
          { internalType: 'uint256', name: 'prizeInUSDC', type: 'uint256' },
          {
            internalType: 'enum ProjectLighthouseV11.Direction',
            name: 'direction',
            type: 'uint8',
          },
        ],
        internalType: 'struct ProjectLighthouseV11.TokenPrediction[8]',
        name: 'tokens',
        type: 'tuple[8]',
      },
    ],
    name: 'submitSignal',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'submittedSignalToday',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalAccounts',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalSignals',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'usedRetryToday',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'userDefaultTokens',
    outputs: [
      { internalType: 'address', name: 'ca', type: 'address' },
      { internalType: 'string', name: 'ticker', type: 'string' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'userSignals',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
    name: 'withdrawJBM',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
