export const ABI = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  { inputs: [], name: 'AccountAlreadyExists', type: 'error' },
  { inputs: [], name: 'AccountNotFound', type: 'error' },
  { inputs: [], name: 'AlreadySignaledToday', type: 'error' },
  { inputs: [], name: 'FidAlreadyRegistered', type: 'error' },
  { inputs: [], name: 'InsufficientJBM', type: 'error' },
  { inputs: [], name: 'InsufficientUSDC', type: 'error' },
  { inputs: [], name: 'InvalidDirection', type: 'error' },
  { inputs: [], name: 'InvalidFid', type: 'error' },
  { inputs: [], name: 'InvalidMarketCap', type: 'error' },
  { inputs: [], name: 'InvalidTokenAddress', type: 'error' },
  { inputs: [], name: 'JBMTransferFailed', type: 'error' },
  { inputs: [], name: 'NoRetryAvailable', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'OwnableInvalidOwner',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'OwnableUnauthorizedAccount',
    type: 'error',
  },
  { inputs: [], name: 'SessionAlreadyActive', type: 'error' },
  { inputs: [], name: 'SessionExpiredError', type: 'error' },
  { inputs: [], name: 'SessionNotActive', type: 'error' },
  { inputs: [], name: 'SignalNotActive', type: 'error' },
  { inputs: [], name: 'SignalNotFound', type: 'error' },
  { inputs: [], name: 'USDCTransferFailed', type: 'error' },
  { inputs: [], name: 'UserBanned', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'timestamp',
        type: 'uint64',
      },
    ],
    name: 'AccountCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'startTime',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'expiresAt',
        type: 'uint64',
      },
    ],
    name: 'SessionStarted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'signalId',
        type: 'uint256',
      },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'expiresAt',
        type: 'uint64',
      },
    ],
    name: 'SignalCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'signalId',
        type: 'uint256',
      },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      {
        indexed: false,
        internalType: 'enum ProjectLighthouseV12.Status',
        name: 'status',
        type: 'uint8',
      },
      {
        indexed: false,
        internalType: 'uint8',
        name: 'correctPredictions',
        type: 'uint8',
      },
    ],
    name: 'SignalSettled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'user', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'fid', type: 'uint256' },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'expiresAt',
        type: 'uint64',
      },
    ],
    name: 'Subscribed',
    type: 'event',
  },
  {
    inputs: [],
    name: 'JBM_RETRY_COST',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'JBM_TOKEN',
    outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_MARKET_CAP',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_USERNAME_LENGTH',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'SESSION_DURATION',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'SUBSCRIPTION_DURATION',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'SUBSCRIPTION_PRICE',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'USDC_TOKEN',
    outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'accounts',
    outputs: [
      { internalType: 'uint256', name: 'fid', type: 'uint256' },
      { internalType: 'uint64', name: 'createdAt', type: 'uint64' },
      { internalType: 'bool', name: 'isBanned', type: 'bool' },
      { internalType: 'bool', name: 'isSubscriber', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'banAccount',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'fid', type: 'uint256' }],
    name: 'createAccount',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'currentSession',
    outputs: [
      { internalType: 'address', name: 'user', type: 'address' },
      { internalType: 'uint256', name: 'fid', type: 'uint256' },
      { internalType: 'uint64', name: 'startTime', type: 'uint64' },
      { internalType: 'bool', name: 'isActive', type: 'bool' },
      { internalType: 'bool', name: 'usedRetry', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'deploymentTimestamp',
    outputs: [{ internalType: 'uint64', name: '', type: 'uint64' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'fidToAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'getAccount',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'fid', type: 'uint256' },
          { internalType: 'uint64', name: 'createdAt', type: 'uint64' },
          { internalType: 'bool', name: 'isBanned', type: 'bool' },
          { internalType: 'bool', name: 'isSubscriber', type: 'bool' },
        ],
        internalType: 'struct ProjectLighthouseV12.Account',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getContractStats',
    outputs: [
      { internalType: 'uint256', name: '_totalSignals', type: 'uint256' },
      { internalType: 'uint256', name: '_totalAccounts', type: 'uint256' },
      {
        internalType: 'uint256',
        name: '_deploymentTimestamp',
        type: 'uint256',
      },
      { internalType: 'uint256', name: '_usdcBalance', type: 'uint256' },
      { internalType: 'uint256', name: '_jbmBalance', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'signalId', type: 'uint256' }],
    name: 'getSignal',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'fid', type: 'uint256' },
          {
            components: [
              { internalType: 'address', name: 'ca', type: 'address' },
              { internalType: 'uint64', name: 'mc', type: 'uint64' },
              { internalType: 'uint8', name: 'direction', type: 'uint8' },
            ],
            internalType: 'struct ProjectLighthouseV12.TokenPrediction[8]',
            name: 'tokens',
            type: 'tuple[8]',
          },
          { internalType: 'uint64', name: 'createdAt', type: 'uint64' },
          { internalType: 'uint64', name: 'expiresAt', type: 'uint64' },
          { internalType: 'uint8', name: 'correctPredictions', type: 'uint8' },
          {
            internalType: 'enum ProjectLighthouseV12.Status',
            name: 'status',
            type: 'uint8',
          },
        ],
        internalType: 'struct ProjectLighthouseV12.Signal',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getUserDailyStatus',
    outputs: [
      { internalType: 'bool', name: 'hasSignaledToday', type: 'bool' },
      { internalType: 'bool', name: 'hasUsedRetry', type: 'bool' },
      { internalType: 'bool', name: 'canSignal', type: 'bool' },
      { internalType: 'bool', name: 'canRetry', type: 'bool' },
      { internalType: 'bool', name: 'isUserSubscriber', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'fid', type: 'uint256' }],
    name: 'getUserSignals',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
    name: 'isSubscriber',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'lastSignalDay',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'loadMiniapp',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nextSignalId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'purchaseRetry',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'signalId', type: 'uint256' },
      { internalType: 'uint64[8]', name: 'exitMarketCaps', type: 'uint64[8]' },
    ],
    name: 'settleSignal',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'signals',
    outputs: [
      { internalType: 'uint256', name: 'fid', type: 'uint256' },
      { internalType: 'uint64', name: 'createdAt', type: 'uint64' },
      { internalType: 'uint64', name: 'expiresAt', type: 'uint64' },
      { internalType: 'uint8', name: 'correctPredictions', type: 'uint8' },
      {
        internalType: 'enum ProjectLighthouseV12.Status',
        name: 'status',
        type: 'uint8',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: 'ca', type: 'address' },
          { internalType: 'uint64', name: 'mc', type: 'uint64' },
          { internalType: 'uint8', name: 'direction', type: 'uint8' },
        ],
        internalType: 'struct ProjectLighthouseV12.TokenPrediction[8]',
        name: 'tokens',
        type: 'tuple[8]',
      },
    ],
    name: 'submitSignal',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'submittedSignalToday',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'subscribe',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'subscriptionExpiry',
    outputs: [{ internalType: 'uint64', name: '', type: 'uint64' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalAccounts',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalSignals',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'usedRetryToday',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'userSignals',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
    name: 'withdrawJBM',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
    name: 'withdrawUSDC',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
